#!/usr/bin/env python3
"""
unified_ingestor.py

Orchestrates ingestion from MULTIPLE sources:
  1. JSearch API (active search)
  2. Gmail (email alerts)
  3. Deduplicates across sources
  4. Saves to data/raw_jobs/all_jobs_{data}.json

Usage:
  python src/unified_ingestor.py
"""

import os
import sys
import json
import glob
import re
from datetime import datetime, timezone
from typing import List, Dict, Any

def normalize_title(title: str) -> str:
    title = title.lower().strip()
    title = re.sub(r"[^\w\s]", " ", title)
    title = re.sub(r"\s+", " ", title)
    return title.strip()





def load_email_jobs() -> List[Dict[str, Any]]:
    """Loads jobs parsed from emails (generated by agents/email_parser_local.py)."""
    filepath = "digests/parsed_jobs_latest.json"
    if not os.path.exists(filepath):
        print("  ℹ️  No parsed email file.")
        return []
    with open(filepath, "r", encoding="utf-8") as f:
        jobs = json.load(f)
    print(f"  ✅ Email: {len(jobs)} jobs from {filepath}")
    return jobs



def load_adzuna_jobs() -> List[Dict[str, Any]]:
    """Loads Adzuna jobs (generated by agents/adzuna_ingestor.py)."""
    files = sorted(glob.glob("data/raw_jobs/adzuna_*.json"))
    if not files:
        print("  ℹ️  No Adzuna file.")
        return []
    latest = files[-1]
    try:
        with open(latest, "r", encoding="utf-8") as f:
            jobs = json.load(f)
        print(f"  ✅ Adzuna: {len(jobs)} jobs from {latest}")
        return jobs
    except (json.JSONDecodeError, IOError) as e:
        print(f"  ⚠️  Error loading {latest}: {e}")
        return []


def normalize_job_fields(job: Dict[str, Any]) -> Dict[str, Any]:
    """Normalizes job fields to the pipeline's canonical English keys, filling defaults."""
    return {
        "company": job.get("company") or job.get("company", "Unknown"),
        "title": job.get("title") or job.get("title", "Unknown"),
        "location": job.get("location") or job.get("location", "Unknown"),
        "description": job.get("description") or job.get("description", ""),
        "url": job.get("url", ""),
        "portal": job.get("portal", "unknown"),
        "language": job.get("language", "en"),
        "posted_at": job.get("posted_at") or job.get("posted_at", datetime.now(timezone.utc).isoformat()),
    }


from utils import deduplicate_jobs, is_off_target_title, max_evaluations_per_run
from deduplicator import filter_new_jobs


def save_unified(jobs: List[Dict[str, Any]]) -> str:
    os.makedirs("data/raw_jobs", exist_ok=True)
    filepath = f"data/raw_jobs/all_jobs_{datetime.now().strftime('%Y%m%d_%H%M')}.json"
    with open(filepath, "w", encoding="utf-8") as f:
        json.dump(jobs, f, ensure_ascii=False, indent=2)
    print(f"  💾 {len(jobs)} unified jobs → {filepath}")
    return filepath


def save_evaluator_input(jobs: List[Dict[str, Any]], db_path: str = None) -> str:
    """Saves in the format the evaluator/digest/dashboard expect.

    Applies the persistent (SQLite) deduplication: jobs already seen in a
    previous run within the retention window are filtered out, so the
    evaluator only spends API calls on genuinely new jobs.

    Cost cap WITHOUT silent loss: jobs beyond the per-run cap are NOT
    marked as seen -- they resurface as new on the next run (a queue).
    The old order (dedup marked everything as seen, then the evaluator
    sliced [:30]) silently swallowed jobs 31+ forever: never evaluated,
    and filtered out of every later run as "already seen".
    """
    os.makedirs("digests", exist_ok=True)
    filepath = "digests/new_jobs_latest.json"
    normalized_jobs = [normalize_job_fields(j) for j in jobs]

    db_kwargs = {"db_path": db_path} if db_path else {}
    reevaluate = os.environ.get("REEVALUATE_ALL", "").lower() in ("1", "true", "yes")
    # REEVALUATE_ALL is a TEST-MODE escape hatch (the workflow's `reevaluate`
    # input). It re-scores jobs already marked as seen, which is the only way
    # to exercise the pipeline end to end without spending job-board quota on
    # a fresh fetch. It costs real LLM calls, so it is opt-in and never set
    # by the scheduled runs.
    if reevaluate:
        fresh_jobs = normalized_jobs
        already_seen = 0
        print(f"  🔁 Cross-run dedup: SKIPPED (REEVALUATE_ALL) -- "
              f"re-scoring all {len(fresh_jobs)} jobs")
    else:
        fresh_jobs = filter_new_jobs(normalized_jobs, mark_seen=False, **db_kwargs)
        already_seen = len(normalized_jobs) - len(fresh_jobs)
        print(f"  🔁 Cross-run dedup: {len(fresh_jobs)} new | {already_seen} already seen (tracker/jobs.db)")

    # Drop clearly off-target postings BEFORE anything is spent on them. The
    # scorer already rejects these correctly, but only after paying for an LLM
    # call out of a cap that good jobs then cannot reach. Validated against
    # every scored title in the history: the highest score among everything
    # this gate rejects is 35, well under the SKIP threshold. See
    # utils.is_off_target_title for why a keyword blacklist was rejected.
    #
    # They are NOT marked as seen: the gate is free to re-apply next run, and
    # not persisting the decision means loosening it later brings them back.
    #
    # Operates on fresh_jobs: filtering normalized_jobs here used to leave
    # fresh_jobs untouched -- the gate logged its drops while the dropped
    # jobs still flowed to the scorer (dead gate, found 2026-08-24).
    before_gate = len(fresh_jobs)
    fresh_jobs = [j for j in fresh_jobs if not is_off_target_title(j.get("title"))]
    dropped = before_gate - len(fresh_jobs)
    if dropped:
        print(f"  🚫 Relevance gate: {dropped} clearly off-target "
              f"(marketing/sales/M&A with no technical element) dropped before scoring.")
    new_after_dedup = len(fresh_jobs) + dropped

    # Spend the budget on the jobs it can buy the most with. Sources arrive
    # in a fixed order -- e-mail alerts first, Adzuna after -- and the cap
    # slices the FIRST n, so the least informative jobs were systematically
    # consuming it: an alert card carries 0 characters and can only ever
    # produce a title-based score capped at REVIEW, while a 500-char Adzuna
    # teaser can be expanded to the full posting by posting_resolver and
    # produce a real decision. Ordering by description length is a stable
    # sort, so it only moves jobs across that quality line and leaves the
    # order within each group alone. Nothing is starved: whatever exceeds the
    # cap stays unseen and comes back on the next run.
    fresh_jobs.sort(key=lambda j: len((j.get("description") or "").strip()), reverse=True)

    cap = max_evaluations_per_run()
    deferred = 0
    if len(fresh_jobs) > cap:
        deferred = len(fresh_jobs) - cap
        print(f"  💰 Cost guard: {len(fresh_jobs)} new jobs, evaluating the first {cap}; "
              f"{deferred} stay unseen and come back next run.")
        fresh_jobs = fresh_jobs[:cap]

    # Only the jobs that WILL be evaluated get marked as seen.
    filter_new_jobs(fresh_jobs, mark_seen=True, **db_kwargs)

    # Where postings stop on their way to the scorer -- read by
    # email_notifier's quiet-day heartbeat and useful on its own.
    stats = {
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "total_ingested": len(normalized_jobs),
        "already_seen": already_seen,
        "new_after_dedup": new_after_dedup,
        "dropped_off_target": dropped,
        "deferred_by_cap": deferred,
        "sent_to_evaluator": len(fresh_jobs),
        "reevaluate_all": reevaluate,
    }
    with open("digests/ingestion_stats_latest.json", "w", encoding="utf-8") as f:
        json.dump(stats, f, ensure_ascii=False, indent=2)

    with open(filepath, "w", encoding="utf-8") as f:
        json.dump(fresh_jobs, f, ensure_ascii=False, indent=2)
    print(f"  💾 {len(fresh_jobs)} jobs → {filepath}")
    return filepath


def main():
    print("=" * 70)
    print("🔗 UNIFIED INGESTOR — Adzuna + e-mail alerts")
    print("=" * 70)

    email_jobs = load_email_jobs()
    adzuna_jobs = load_adzuna_jobs()

    # Two sources were removed on 2026-08-23 with the code that fed them:
    # JSearch (agents/jsearch_ingestor.py) and LinkedIn, which had been
    # disabled in the workflow for consistently returning 0 jobs. Both
    # loaders were still running every day and printing "No X file",
    # which reads like a source that exists and happens to be empty.
    all_jobs = email_jobs + adzuna_jobs
    if not all_jobs:
        print("\n⚠️  No jobs from any source.")
        return None

    unique = deduplicate_jobs(all_jobs)
    print(f"\n📊 Total: {len(all_jobs)} | After dedup: {len(unique)}")

    save_unified(unique)
    filepath = save_evaluator_input(unique)
    return filepath


if __name__ == "__main__":
    main()
