#!/usr/bin/env python3
"""
unified_ingestor.py

Orchestrates ingestion from MULTIPLE sources:
  1. JSearch API (active search)
  2. Gmail (email alerts)
  3. Deduplicates across sources
  4. Saves to data/raw_jobs/all_jobs_{data}.json

Usage:
  python src/unified_ingestor.py
"""

import os
import sys
import json
import glob
import re
from datetime import datetime, timezone
from typing import List, Dict, Any

def normalize_title(title: str) -> str:
    title = title.lower().strip()
    title = re.sub(r"[^\w\s]", " ", title)
    title = re.sub(r"\s+", " ", title)
    return title.strip()




def load_jsearch_jobs() -> List[Dict[str, Any]]:
    files = sorted(glob.glob("data/raw_jobs/jsearch_*.json"))
    if not files:
        print("  ℹ️  No JSearch file.")
        return []
    latest = files[-1]
    try:
        with open(latest, "r", encoding="utf-8") as f:
            jobs = json.load(f)
        print(f"  ✅ JSearch: {len(jobs)} jobs from {latest}")
        return jobs
    except (json.JSONDecodeError, IOError) as e:
        print(f"  ⚠️  Error loading {latest}: {e}")
        return []


def load_email_jobs() -> List[Dict[str, Any]]:
    """Loads jobs parsed from emails (generated by agents/email_parser.py)."""
    filepath = "digests/parsed_jobs_latest.json"
    if not os.path.exists(filepath):
        print("  ℹ️  No parsed email file.")
        return []
    with open(filepath, "r", encoding="utf-8") as f:
        jobs = json.load(f)
    print(f"  ✅ Email: {len(jobs)} jobs from {filepath}")
    return jobs


def load_linkedin_jobs() -> List[Dict[str, Any]]:
    """Loads LinkedIn jobs (generated by agents/linkedin_ingestor.py)."""
    files = sorted(glob.glob("data/raw_jobs/linkedin_*.json"))
    if not files:
        print("  ℹ️  No LinkedIn file.")
        return []
    latest = files[-1]
    try:
        with open(latest, "r", encoding="utf-8") as f:
            jobs = json.load(f)
        print(f"  ✅ LinkedIn: {len(jobs)} jobs from {latest}")
        return jobs
    except (json.JSONDecodeError, IOError) as e:
        print(f"  ⚠️  Error loading {latest}: {e}")
        return []


def load_adzuna_jobs() -> List[Dict[str, Any]]:
    """Loads Adzuna jobs (generated by agents/adzuna_ingestor.py)."""
    files = sorted(glob.glob("data/raw_jobs/adzuna_*.json"))
    if not files:
        print("  ℹ️  No Adzuna file.")
        return []
    latest = files[-1]
    try:
        with open(latest, "r", encoding="utf-8") as f:
            jobs = json.load(f)
        print(f"  ✅ Adzuna: {len(jobs)} jobs from {latest}")
        return jobs
    except (json.JSONDecodeError, IOError) as e:
        print(f"  ⚠️  Error loading {latest}: {e}")
        return []


def normalize_to_legacy(job: Dict[str, Any]) -> Dict[str, Any]:
    """Converts fields from the new format (JSearch) to the pipeline's legacy format."""
    return {
        "empresa": job.get("company") or job.get("empresa", "Unknown"),
        "titulo": job.get("title") or job.get("titulo", "Unknown"),
        "localizacao": job.get("location") or job.get("localizacao", "Unknown"),
        "descricao": job.get("description") or job.get("descricao", ""),
        "url": job.get("url", ""),
        "portal": job.get("portal", "unknown"),
        "idioma": job.get("idioma", "en"),
        "data_post": job.get("posted_at") or job.get("data_post", datetime.now(timezone.utc).isoformat()),
    }


from utils import deduplicate_jobs
from deduplicator import filter_new_jobs


def save_unified(jobs: List[Dict[str, Any]]) -> str:
    os.makedirs("data/raw_jobs", exist_ok=True)
    filepath = f"data/raw_jobs/all_jobs_{datetime.now().strftime('%Y%m%d_%H%M')}.json"
    with open(filepath, "w", encoding="utf-8") as f:
        json.dump(jobs, f, ensure_ascii=False, indent=2)
    print(f"  💾 {len(jobs)} unified jobs → {filepath}")
    return filepath


def save_legacy_format(jobs: List[Dict[str, Any]]) -> str:
    """Saves in the format the legacy pipeline (evaluator, digest, etc.) expects.

    Applies the persistent (SQLite) deduplication: jobs already seen in a
    previous run within the retention window are filtered out, so the
    evaluator only spends API calls on genuinely new jobs.
    """
    os.makedirs("digests", exist_ok=True)
    filepath = "digests/new_jobs_latest.json"
    legacy_jobs = [normalize_to_legacy(j) for j in jobs]

    fresh_jobs = filter_new_jobs(legacy_jobs)
    already_seen = len(legacy_jobs) - len(fresh_jobs)
    print(f"  🔁 Cross-run dedup: {len(fresh_jobs)} new | {already_seen} already seen (tracker/jobs.db)")

    with open(filepath, "w", encoding="utf-8") as f:
        json.dump(fresh_jobs, f, ensure_ascii=False, indent=2)
    print(f"  💾 {len(fresh_jobs)} jobs (legacy format) → {filepath}")
    return filepath


def main():
    print("=" * 70)
    print("🔗 UNIFIED INGESTOR — JSearch + Email")
    print("=" * 70)

    jsearch_jobs = load_jsearch_jobs()
    email_jobs = load_email_jobs()
    linkedin_jobs = load_linkedin_jobs()
    adzuna_jobs = load_adzuna_jobs()

    all_jobs = jsearch_jobs + email_jobs + linkedin_jobs + adzuna_jobs
    if not all_jobs:
        print("\n⚠️  No jobs from any source.")
        return None

    unique = deduplicate_jobs(all_jobs)
    print(f"\n📊 Total: {len(all_jobs)} | After dedup: {len(unique)}")

    save_unified(unique)
    filepath = save_legacy_format(unique)
    return filepath


if __name__ == "__main__":
    main()
